name: publish

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'deploy content'
        required: true
        default: 'default content'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        mkdir content
        touch content/sample.html
        git add .
        git commit -m 'add content'
        git push origin main